// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI4zuhH3mMKRHPrs4Tt6o7OfZ1GEJSu2g',
    appId: '1:978426860847:web:8ab8c54115ca16120e3dda',
    messagingSenderId: '978426860847',
    projectId: 'stylesync-6a6fa',
    authDomain: 'stylesync-6a6fa.firebaseapp.com',
    storageBucket: 'stylesync-6a6fa.firebasestorage.app',
    measurementId: 'G-CZR6KVXKFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1BBrYcIstrwZ4tWZJtx4pqhHmt8_5LY',
    appId: '1:978426860847:android:023f3254414909260e3dda',
    messagingSenderId: '978426860847',
    projectId: 'stylesync-6a6fa',
    storageBucket: 'stylesync-6a6fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKd6FAdx8sjAM_vSpN4ZC_Vl4fQMx3VJM',
    appId: '1:978426860847:ios:76448ba142aee32d0e3dda',
    messagingSenderId: '978426860847',
    projectId: 'stylesync-6a6fa',
    storageBucket: 'stylesync-6a6fa.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKd6FAdx8sjAM_vSpN4ZC_Vl4fQMx3VJM',
    appId: '1:978426860847:ios:76448ba142aee32d0e3dda',
    messagingSenderId: '978426860847',
    projectId: 'stylesync-6a6fa',
    storageBucket: 'stylesync-6a6fa.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI4zuhH3mMKRHPrs4Tt6o7OfZ1GEJSu2g',
    appId: '1:978426860847:web:81d22341c93d917a0e3dda',
    messagingSenderId: '978426860847',
    projectId: 'stylesync-6a6fa',
    authDomain: 'stylesync-6a6fa.firebaseapp.com',
    storageBucket: 'stylesync-6a6fa.firebasestorage.app',
    measurementId: 'G-JZ9YZK0D6V',
  );
}
